added create item popup
OlgaPinchuk/Tredara-frontend pull request #2
Opened 2023-10-03 12:13 UTC by aggarrohit

2023-10-03 17:53 UTC, OlgaPinchuk requested changes

2023-10-03 17:53 UTC, OlgaPinchuk commented on src/components/CreateItem.jsx
> +            type="text"
I think textarea does not have "type" attribute

2023-10-03 17:53 UTC, OlgaPinchuk commented on src/components/CreateItem.jsx
> +          <input
I have added InputField component. Maybe it's better to refactor and use it instead? But it is up to you to decide

2023-10-03 17:53 UTC, OlgaPinchuk commented on src/components/CreateItem.jsx
> +    console.log("item is : " + JSON.stringify(data));
If you do not need  console.log we can remove it

2023-10-03 17:53 UTC, OlgaPinchuk commented on src/components/CreateItem.jsx
> +    }
may be we can replace these if-checks with required attribute on inputs

2023-10-03 17:53 UTC, OlgaPinchuk commented on src/components/CreateItem.jsx
> +          <button className="bottom-button" onClick={handleAddButtonClick}>
It is better to handle onSubmit event on form but we need not to forget e.preventDefault() at the beginning of function body

2023-10-03 17:53 UTC, OlgaPinchuk commented on src/styles/components/create-item-container.css
> +/* .input-image {
Do you need this code in comments?

2023-10-03 17:53 UTC, OlgaPinchuk commented on src/components/CreateItem.jsx
> +        response.json().then((resp) => onSuccess(resp));
I can't find these functions (onSuccess, onFailure)

2023-10-03 18:21 UTC, rashmoni approved these changes

2023-10-04 04:35 UTC, aggarrohit commented on src/components/CreateItem.jsx
> +            type="text"
Removed type from text-area

2023-10-04 04:36 UTC, aggarrohit commented on src/components/CreateItem.jsx
> +          <input
the create item form has 3 types of input fields so keeping as it is for now but will refactor in future

2023-10-04 04:36 UTC, aggarrohit commented on src/components/CreateItem.jsx
> +    console.log("item is : " + JSON.stringify(data));
removed

2023-10-04 04:36 UTC, aggarrohit commented on src/components/CreateItem.jsx
> +    }
done

2023-10-04 04:37 UTC, aggarrohit commented on src/components/CreateItem.jsx
> +          <button className="bottom-button" onClick={handleAddButtonClick}>
done

2023-10-04 04:37 UTC, aggarrohit commented on src/styles/components/create-item-container.css
> +/* .input-image {
removed

2023-10-04 04:37 UTC, aggarrohit commented on src/components/CreateItem.jsx
> +        response.json().then((resp) => onSuccess(resp));
add these during API integration

2023-10-04 08:14 UTC, OlgaPinchuk approved these changes

2023-10-04 08:14 UTC, AlirezaKToosi approved these changes

2023-10-04 08:14 UTC, merged